wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: episode
      6:
      - 3
    - 1: reward
      5: 1
      6:
      - 1
      - 3
    python_version: 3.8.10
    start_time: 1645126202
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 7
      4: 3.8.10
      5: 0.12.10
      8:
      - 3
      - 5
